import { McleodCandidate } from "./types";

export const MOCK_CANDIDATES: McleodCandidate[] = [
  {
    orderId: "12345678",
    movementId: "mov-001",
    customerId: "BACOMCTX",
    customerName: "Baco Trading",
    blnum: "DF917 88 BALES",
    consigneeRefNo: "DF917",
    originActualArrival: null,
    originActualDeparture: null,
    destActualArrival: null,
    destActualDeparture: null,
    schedOriginEarly: "2024-02-10",
    schedOriginLate: null,
    schedDestEarly: "2024-02-12",
    schedDestLate: null,
    movementStatus: "a",
    brokerageStatus: "active",
  },
  {
    orderId: "87654321",
    movementId: "mov-002",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    blnum: "598 100 B/C",
    consigneeRefNo: "598",
    originActualArrival: "2026-01-01",
    originActualDeparture: "2026-01-01",
    destActualArrival: null,
    destActualDeparture: null,
    schedOriginEarly: "2026-01-01",
    schedOriginLate: null,
    schedDestEarly: "2026-01-02",
    schedDestLate: null,
    movementStatus: "a",
    brokerageStatus: "active",
  },
];