import { CustomerXrefRow } from "./types";

export const CUSTOMER_XREF: CustomerXrefRow[] = [
  {
    alias: "BUNGE",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "BUNG",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "BUNGOMNE",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "BUNGE USA AGRICULTURE",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "BUNGE USA AGRICULTURE LLC",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "VITERRA",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "GLENCORE",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "GLENCORE AGRICULTURE",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },

  {
    alias: "BACO",
    canonicalCustomer: "BACO",
    customerId: "BACOMCTX",
    customerName: "Baco Trading",
    active: true,
  },

  {
    alias: "ALLENBERG",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "LDC",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "ALLENBURG",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "ALLEN",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },

  {
    alias: "STAPL",
    canonicalCustomer: "STAPL",
    customerId: "STAPGRMS",
    customerName: "STAPLCOTN CO OP ASSN",
    active: true,
  },
  {
    alias: "STAPLE",
    canonicalCustomer: "STAPL",
    customerId: "STAPGRMS",
    customerName: "STAPLCOTN CO OP ASSN",
    active: true,
  },
  {
    alias: "STAP",
    canonicalCustomer: "STAPL",
    customerId: "STAPGRMS",
    customerName: "STAPLCOTN CO OP ASSN",
    active: true,
  },

  {
    alias: "OLAM",
    canonicalCustomer: "OLAM",
    customerId: "OLAMRITX",
    customerName: "Olam Cotton",
    active: true,
  },
  {
    alias: "OLAM COTTON",
    canonicalCustomer: "OLAM",
    customerId: "OLAMRITX",
    customerName: "Olam Cotton",
    active: true,
  },
  {
    alias: "QUEENSLAND",
    canonicalCustomer: "OLAM",
    customerId: "OLAMRITX",
    customerName: "Olam Cotton",
    active: true,
  },
  {
    alias: "BRIGHTFIELD",
    canonicalCustomer: "OLAM",
    customerId: "OLAMRITX",
    customerName: "Olam Cotton",
    active: true,
  },

  {
    alias: "COFCO",
    canonicalCustomer: "COFCO",
    customerId: "NOBLHOTX",
    customerName: "COFCO Americas Resources Corp.",
    active: true,
  },
  {
    alias: "NOBLE",
    canonicalCustomer: "COFCO",
    customerId: "NOBLHOTX",
    customerName: "COFCO Americas Resources Corp.",
    active: true,
  },
  {
    alias: "NOBL",
    canonicalCustomer: "COFCO",
    customerId: "NOBLHOTX",
    customerName: "COFCO Americas Resources Corp.",
    active: true,
  },

  {
    alias: "ADM",
    canonicalCustomer: "ADM",
    customerId: "ADMCLUTX",
    customerName: "ADM Cotton",
    active: true,
  },

  {
    alias: "MEMTEX",
    canonicalCustomer: "MEMTEX",
    customerId: "MEMTLUTX",
    customerName: "MEMTEX Cotton Marketing",
    active: true,
  },
  {
    alias: "MEM",
    canonicalCustomer: "MEMTEX",
    customerId: "MEMTLUTX",
    customerName: "MEMTEX Cotton Marketing",
    active: true,
  },

  {
    alias: "TOYO",
    canonicalCustomer: "TOYO",
    customerId: "TOYODATX",
    customerName: "Toyo Cotton Company",
    active: true,
  },

  {
    alias: "WHITEGOLD",
    canonicalCustomer: "WHITE GOLD",
    customerId: "WHITBACA",
    customerName: "White Gold Association,Inc",
    active: true,
  },
  {
    alias: "WHITE",
    canonicalCustomer: "WHITE GOLD",
    customerId: "WHITBACA",
    customerName: "White Gold Association,Inc",
    active: true,
  },

  {
    alias: "TERRANOVA",
    canonicalCustomer: "TERRA NOVA",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
    alias: "TERRANOVE",
    canonicalCustomer: "TERRA NOVA",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
    alias: "TERRA",
    canonicalCustomer: "TERRA NOVA",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
    alias: "NOVA",
    canonicalCustomer: "TERRA NOVA",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },

  {
    alias: "ED&FMAN",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "ED & FMAN",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "EDFMAN",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "EDF",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "ED & F MAN",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "ED&F MAN",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "ED F MAN",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "EDFM",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "EDFMAN COTTON",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
  {
    alias: "EFDM",
    canonicalCustomer: "ED&F MAN",
    customerId: "EDFMHOTX",
    customerName: "ED&F Man Cotton LLC",
    active: true,
  },
];