import { CustomerXrefRow } from "./types";

export const CUSTOMER_XREF: CustomerXrefRow[] = [
  {
    alias: "BUNGE",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "BUNG",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "VITERRA",
    canonicalCustomer: "BUNGE",
    customerId: "BUNGOMNE",
    customerName: "Bunge USA Agriculture, LLC.",
    active: true,
  },
  {
    alias: "BACO",
    canonicalCustomer: "BACO",
    customerId: "BACOMCTX",
    customerName: "Baco Trading",
    active: true,
  },
  {
    alias: "ALLENBERG",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "LDC",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "ALLENBURG",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "ALLEN",
    canonicalCustomer: "LDC",
    customerId: "ALLECOTN",
    customerName: "Allenberg Cotton Co.",
    active: true,
  },
  {
    alias: "STAPL",
    canonicalCustomer: "StaplCotn",
    customerId: "STAPGRMS",
    customerName: "STAPLCOTN CO OP ASSN",
    active: true,
  },
  {
    alias: "STAPLE",
    canonicalCustomer: "StaplCotn",
    customerId: "STAPGRMS",
    customerName: "STAPLCOTN CO OP ASSN",
    active: true,
  },
  {
    alias: "STAP",
    canonicalCustomer: "StaplCotn",
    customerId: "STAPGRMS",
    customerName: "STAPLCOTN CO OP ASSN",
    active: true,
  },
  {
    alias: "OLAM",
    canonicalCustomer: "Olam Cotton",
    customerId: "OLAMRITX",
    customerName: "Olam Cotton",
    active: true,
  },
  {
    alias: "QUEENSLAND",
    canonicalCustomer: "Olam Cotton",
    customerId: "OLAMRITX",
    customerName: "Olam Cotton",
    active: true,
  },
  {
    alias: "COFCO",
    canonicalCustomer: "Cofco",
    customerId: "NOBLHOTX",
    customerName: "COFCO Americas Resources Corp.",
    active: true,
  },
  {
    alias: "NOBLE",
    canonicalCustomer: "Cofco",
    customerId: "NOBLHOTX",
    customerName: "COFCO Americas Resources Corp.",
    active: true,
  },
  {
    alias: "NOBL",
    canonicalCustomer: "Cofco",
    customerId: "NOBLHOTX",
    customerName: "COFCO Americas Resources Corp.",
    active: true,
  },
  {
    alias: "ADM",
    canonicalCustomer: "ADM Cotton",
    customerId: "ADMCLUTX",
    customerName: "ADM Cotton",
    active: true,
  },
  {
    alias: "MEMTEX",
    canonicalCustomer: "MEMTEX Cotton Marketing",
    customerId: "MEMTLUTX",
    customerName: "MEMTEX Cotton Marketing",
    active: true,
  },
  {
    alias: "MEM",
    canonicalCustomer: "MEMTEX Cotton Marketing",
    customerId: "MEMTLUTX",
    customerName: "MEMTEX Cotton Marketing",
    active: true,
  },
  {
    alias: "TOYO",
    canonicalCustomer: "Toyo Cotton Company",
    customerId: "TOYODATX",
    customerName: "Toyo Cotton Company",
    active: true,
  },
  {
    alias: "WHITEGOLD",
    canonicalCustomer: "White Gold Association,Inc",
    customerId: "WHITBACA",
    customerName: "White Gold Association,Inc",
    active: true,
  },
  {
    alias: "WHITE",
    canonicalCustomer: "White Gold Association,Inc",
    customerId: "WHITBACA",
    customerName: "White Gold Association,Inc",
    active: true,
  },
  {
    alias: "TERRANOVA",
    canonicalCustomer: "Terra Nova Commodities LLC",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
    alias: "TERRANOVE",
    canonicalCustomer: "Terra Nova Commodities LLC",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
    alias: "TERRA",
    canonicalCustomer: "Terra Nova Commodities LLC",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
    alias: "NOVA",
    canonicalCustomer: "Terra Nova Commodities LLC",
    customerId: "TERRLUTX",
    customerName: "Terra Nova Commodities LLC",
    active: true,
  },
  {
  alias: "ED&FMAN",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
{
  alias: "ED & FMAN",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
{
  alias: "EDFMAN",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
{
  alias: "EDF",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
{
  alias: "ED & F MAN",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
{
  alias: "ED&F MAN",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
{
  alias: "ED F MAN",
  canonicalCustomer: "ED&F MAN",
  customerId: "EDFMHOTX",
  customerName: "ED&F Man Cotton LLC",
  active: true,
},
];